dotenv: .env
accounts:
  Metamask_dev: ${PRIVATE_KEY}
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    optimize: true
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
networks:
  default: ganache-local-gui
  ganache-local-gui:
    USDETHFeed: ''
    verify: False
  rinkeby:
    USDETHFeed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet:
    USDETHFeed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: True
